import type { Metadata } from "next";
import DetailPage from "../components/DetailPage";
export const metadata: Metadata = { title: "About Us", description: "Learn how Fiplex Company Limited combines industrial communication technology and software engineering for enterprise solutions." };
export default function AboutPage() { return <DetailPage code="about" sw={{
  label:"Kuhusu Fiplex", title:"Uhandisi unaolenga matokeo ya biashara.", intro:"Fiplex Company Limited ni kampuni ya teknolojia inayochanganya uelewa wa mazingira ya viwandani na uwezo wa kutengeneza programu za kisasa.",
  points:[{title:"Tunaanza na tatizo",text:"Teknolojia ni chombo. Kila mradi huanza kwa kuelewa shughuli, watumiaji na matokeo yanayohitajika."},{title:"Tunajenga kwa viwango",text:"Usalama, utendaji, urahisi wa matengenezo na uwezo wa kukua huingizwa tangu hatua ya usanifu."},{title:"Tunafanya kazi kwa karibu",text:"Mawasiliano ya wazi na mapitio ya mara kwa mara hufanya timu ya mteja kuwa sehemu ya delivery."},{title:"Tunaangalia mbele",text:"Suluhisho huandaliwa kwa mahitaji ya sasa bila kufunga milango ya maendeleo ya baadaye."}],
  processTitle:"Kanuni zinazoongoza kazi yetu.", process:["Uwazi katika maamuzi na maendeleo","Ubora unaopimika katika delivery","Usalama na ulinzi wa data","Ushirikiano wa muda mrefu"], ctaTitle:"Tujenge hatua inayofuata pamoja.", ctaText:"Fiplex iko Dodoma, Tanzania, na inalenga kutoa suluhisho za biashara zenye thamani ndani na nje ya nchi."
}} en={{
  label:"About Fiplex", title:"Engineering focused on business outcomes.", intro:"Fiplex Company Limited is a technology company combining an understanding of industrial environments with modern software engineering capability.",
  points:[{title:"We start with the problem",text:"Technology is a tool. Every engagement starts by understanding operations, users and the required outcome."},{title:"We build to standards",text:"Security, performance, maintainability and scalability are considered from the architecture stage."},{title:"We work closely",text:"Clear communication and regular reviews make the client team part of the delivery process."},{title:"We look ahead",text:"Solutions meet today’s needs without closing the door on tomorrow’s growth."}],
  processTitle:"Principles that guide our work.", process:["Clarity in decisions and progress","Measurable quality in delivery","Security and data protection","Long-term collaboration"], ctaTitle:"Let’s build what comes next.", ctaText:"Fiplex is based in Dodoma, Tanzania, and is focused on delivering valuable enterprise solutions at home and beyond."
}} />; }
