import type { Metadata } from "next";
import DetailPage from "../components/DetailPage";
export const metadata: Metadata = { title: "Custom Software Development", description: "Custom web, mobile, enterprise platforms, APIs and cloud software built by Fiplex Company Limited." };
export default function SoftwarePage() { return <DetailPage code="software" sw={{
  label:"Maendeleo ya programu", title:"Programu inayolingana na namna biashara yako inavyofanya kazi.", intro:"Tunatengeneza bidhaa za kidijitali zenye matumizi rahisi, msingi imara wa kiufundi na uwezo wa kukua pamoja na biashara yako.",
  points:[{title:"Mifumo ya web",text:"Portal, dashboard, ERP na mifumo maalum ya kusimamia shughuli za ndani na huduma kwa wateja."},{title:"Programu za simu",text:"Mobile apps za Android na iOS zinazolenga uzoefu mzuri, utendaji na uunganishaji wa huduma."},{title:"API na integrations",text:"Huduma za backend na viunganishi vinavyoruhusu mifumo, malipo na data kufanya kazi pamoja."},{title:"Cloud na DevOps",text:"Uwekaji wa mifumo, automation, CI/CD, ufuatiliaji na miundombinu yenye utulivu."}],
  processTitle:"Tunajenga kwa uwazi, hatua kwa hatua.", process:["Kuelewa tatizo, watumiaji na vipaumbele","UX/UI, usanifu wa mfumo na mpango wa delivery","Development, majaribio na mapitio ya pamoja","Deployment, mafunzo na maboresho"], ctaTitle:"Geuza wazo lako kuwa mfumo halisi.", ctaText:"Tunaweza kuanza na MVP, kuboresha mfumo uliopo au kujenga jukwaa kamili la biashara."
}} en={{
  label:"Software development", title:"Software shaped around the way your business works.", intro:"We build digital products with intuitive experiences, strong technical foundations and room to grow with your enterprise.",
  points:[{title:"Web platforms",text:"Portals, dashboards, ERP solutions and custom systems for internal operations and customer services."},{title:"Mobile applications",text:"Android and iOS applications focused on experience, performance and connected services."},{title:"APIs and integrations",text:"Backend services and connectors that enable systems, payments and data to work together."},{title:"Cloud and DevOps",text:"Deployment, automation, CI/CD, monitoring and reliable infrastructure for modern applications."}],
  processTitle:"We build transparently, one clear stage at a time.", process:["Understand the problem, users and priorities","UX/UI, architecture and delivery planning","Development, testing and collaborative review","Deployment, training and improvement"], ctaTitle:"Turn your idea into a real system.", ctaText:"We can start with an MVP, modernise an existing system or build a complete enterprise platform."
}} />; }
