import type { Metadata } from "next";
import DetailPage from "../components/DetailPage";
export const metadata: Metadata = { title: "Industrial Communication Technology", description: "Reliable industrial networks, systems integration, monitoring and secure data connectivity from Fiplex Company Limited." };
export default function TechnologyPage() { return <DetailPage code="technology" sw={{
  label:"Teknolojia za viwandani", title:"Mawasiliano thabiti kwa mazingira muhimu.", intro:"Tunaweka msingi wa kidijitali unaounganisha vifaa, mifumo ya udhibiti na timu za uendeshaji bila kupoteza usalama, mwonekano au uimara.",
  points:[{title:"Mitandao ya viwandani",text:"Usanifu na ujumuishaji wa miundombinu ya mawasiliano inayofaa kwa mazingira ya uzalishaji na uendeshaji."},{title:"Ufuatiliaji wa mifumo",text:"Mwonekano wa hali ya vifaa na mtiririko wa data ili timu zibaini hitilafu mapema na kujibu kwa haraka."},{title:"Ujumuishaji salama",text:"Kuunganisha mifumo mipya na iliyopo kwa kuzingatia ulinzi wa data, upatikanaji na udhibiti wa ufikiaji."},{title:"Miundombinu tayari kukua",text:"Misingi inayoweza kupanuka kadri vituo, vifaa na mahitaji ya biashara yanavyoongezeka."}],
  processTitle:"Kutoka mazingira halisi hadi mfumo unaotegemewa.", process:["Tathmini ya mazingira na mahitaji","Usanifu wa suluhisho na mpango wa ujumuishaji","Utekelezaji, majaribio na uhamishaji wa maarifa","Ufuatiliaji na maboresho endelevu"], ctaTitle:"Unganisha operesheni zako kwa uhakika.", ctaText:"Tueleze mazingira yako, changamoto za mawasiliano na matokeo unayotaka kufikia."
}} en={{
  label:"Industrial technology", title:"Resilient communications for critical environments.", intro:"We create the digital foundation that connects equipment, control systems and operating teams without compromising security, visibility or reliability.",
  points:[{title:"Industrial networks",text:"Design and integration of communications infrastructure suited to production and operating environments."},{title:"Systems monitoring",text:"Visibility into equipment health and data flows so teams detect issues early and respond faster."},{title:"Secure integration",text:"Connecting new and existing systems with data protection, availability and access control in mind."},{title:"Infrastructure built to scale",text:"Foundations that can expand as locations, equipment and enterprise needs grow."}],
  processTitle:"From real environments to reliable systems.", process:["Environment and requirements assessment","Solution architecture and integration plan","Implementation, testing and knowledge transfer","Monitoring and continuous improvement"], ctaTitle:"Connect your operations with confidence.", ctaText:"Tell us about your environment, communication challenges and the outcome you want to achieve."
}} />; }
